org: ranulnd
app: job-search-app
service: job-search-app
frameworkVersion: '3'

provider:
  name: aws
  region: ap-south-1
  runtime: nodejs14.x
  environment:
    COMPANY_TABLE: 
      Ref: CompanyTable
    SEEKER_TABLE:
      Ref: JobSeekerTable
    JOB_TABLE:
      Ref: JobTable
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:DescribeTable
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - "Fn::GetAtt": [CompanyTable, Arn]
            - "Fn::GetAtt": [JobSeekerTable, Arn]
            - "Fn::GetAtt": [JobTable, Arn]
            
plugins:
  - serverless-offline

functions:
  hello:
    handler: /src/handlers/handler.hello
    events:
      - httpApi:
          path: /hello
          method: get
  test:
    handler: handler.test
    events:
      - httpApi:
          path: /
          method: get
  getJobs:
    handler: /src/handlers/getAllJobs.getAllJobs
    events:
      - httpApi:
          path: /getAllJobs
          method: get
          cors: true
  addJobs:
    handler: /src/handlers/addJobs.addJobs
    events:
      - httpApi:
          path: /addJob
          method: post
          cors: true
  deleteJobs:
    handler: /src/handlers/deleteJob.deleteJob
    events:
      - httpApi:
          path: /deleteJob
          method: delete
          cors: true

resources:
  Resources:
    JobSeekerTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: email
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: SeekerDetails
            KeySchema:
              - AttributeName: email
                KeyType: HASH
            Projection:
              ProjectionType: ALL    
        TableName: ${self:service}-jobSeekerTable-${sls:stage}
    CompanyTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: email
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: CompanyDetails
            KeySchema:
              - AttributeName: email
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        TableName: ${self:service}-companyTable-1-${sls:stage}
    JobTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: companyId
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: JobD
            KeySchema:
              - AttributeName: companyId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        TableName: ${self:service}-jobTable-1-${sls:stage} 